role :inception, "ec2-50-17-230-216.compute-1.amazonaws.com"
set :user, "ubuntu"

desc "Prepare inception VM"
task :prepare_inception, :roles => :inception do
  # export ORIGUSER=ubuntu
  run "curl -s https://raw.github.com/drnic/bosh-getting-started/master/scripts/prepare_inception.sh > /tmp/prepare_inception.sh"
  run "chmod +x /tmp/prepare_inception.sh"
  sudo "/tmp/prepare_inception.sh"
  # source /etc/profile
end

desc "Verify bosh micro installed"
task :verify_bosh_micro, :roles => :inception do
  run "bosh help micro"
end